       name: build

       on:
     push:
     branches: 
              - main
              - apnoc-itiversion-1
     jobs:
     build:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v1
     - name: Use Node.js 12.10
       uses: actions/setup-node@v1
       with:
        node-version: '12.10'
    - name: Install yarn and run unittest
      run: |
        yarn
        yarn test
         

      - name: Build and Push Docker Image
         uses: apnoc/iti-website@v4
      with:
        image: nicnoc/iti-website
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}   

